{
 "title": "Discord Alerts Metrics",
 "refresh": "5s",
 "panels": [
  {
   "title": "Container Down",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "container_down",
     "legendFormat": "{{name}} went down at {{stopped_at}} UTC"
    }
   ]
  },
  {
   "title": "Container Unhealthy",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "docker_container_health_status{status=\"unhealthy\"}",
     "legendFormat": "{{name}} became unhealthy at {{detected_at}} UTC"
    }
   ]
  },
  {
   "title": "Container On High CPU",
   "type": "graph",
   "gridPos": { "x": 0, "y": 5, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "container_cpu_alert",
     "legendFormat": "{{name}}'s cpu usage crossed threshold at {{detected_at}} UTC"
    }
   ]
  },
  {
   "title": "Container On High Memory",
   "type": "graph",
   "gridPos": { "x": 12, "y": 5, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "container_memory_alert",
     "legendFormat": "{{name}}'s memory utilization crossed threshold at {{detected_at}} UTC"
    }
   ]
  },
  {
   "title": "Host On High CPU",
   "type": "graph",
   "gridPos": { "x": 0, "y": 10, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "cpu_threshold",
     "legendFormat": "Host's CPU utilization crossed threshold at {{detected_at}} UTC"
    }
   ]
  },
  {
   "title": "Host On High Memory",
   "type": "graph",
   "gridPos": { "x": 12, "y": 10, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{name!=\"\"})/ sum(node_memory_MemTotal_bytes)) * 100 > 80",
     "legendFormat": "Host's memory utilization crossed threshold"
    }
   ]
  }
 ]
}